---
apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterCrawler
metadata:
  name: ocular-defaults-static-list
spec:
  container:
    image: '{{ .Values.crawlers.image.repository }}:{{ .Values.crawlers.image.tag }}'
    name: static-list
    resources: {}
  parameters:
    - description: New line separated list of target identifiers to crawl.
      name: TARGET_IDENTIFIERS
      required: true
