crawlers:
  image:
    repository: "ghcr.io/crashappsec/ocular-default-crawlers"
    tag: "v0.1.6"
downloaders:
  image:
    repository: "ghcr.io/crashappsec/ocular-default-downloaders"
    tag: "v0.1.6"
uploaders:
  image:
    repository: "ghcr.io/crashappsec/ocular-default-uploaders"
    tag: "v0.1.6"
