{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "chalkular.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ include "chalkular.resourceName" (dict "suffix" "mediatypepolicy-editor-role" "context" $) }}
rules:
    - apiGroups:
        - chalk.ocular.crashoverride.run
      resources:
        - mediatypepolicies
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - chalk.ocular.crashoverride.run
      resources:
        - mediatypepolicies/status
      verbs:
        - get
{{- end }}
