apiVersion: v2
name: chalkular
description: Chalkular provides a way for chalk to trigger Ocular pipelines
type: application
version: 0.0.1
appVersion: "0.0.1"
icon: "https://ocularproject.io/favicon-32x32.png"
