{{- if .Values.certManager.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "ocular.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ include "ocular.resourceName" (dict "suffix" "serving-cert" "context" $) }}
    namespace: {{ .Release.Namespace }}
spec:
    dnsNames:
        - {{ include "ocular.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc
        - {{ include "ocular.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc.cluster.local
    issuerRef:
        kind: Issuer
        name: {{ include "ocular.resourceName" (dict "suffix" "selfsigned-issuer" "context" $) }}
    secretName: webhook-server-cert
{{- end }}
