apiVersion: v1
data:
    OCULAR_SEARCH_CLUSTER_ROLE: ocular-search-cluster-role
    OCULAR_SIDECAR_IMG: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
    OCULAR_SIDECAR_PULLPOLICY: IfNotPresent
kind: ConfigMap
metadata:
    name: {{ include "ocular.resourceName" (dict "suffix" "controller-manager-config" "context" $) }}
    namespace: {{ .Release.Namespace }}
