apiVersion: v1
data:
    OCULAR_EXTRACTOR_IMG: "{{ .Values.extractor.image.repository }}:{{ .Values.extractor.image.tag }}"
    OCULAR_EXTRACTOR_PULLPOLICY: IfNotPresent
    OCULAR_SEARCH_CLUSTER_ROLE: ocular-search-cluster-role
kind: ConfigMap
metadata:
    name: {{ include "ocular.resourceName" (dict "suffix" "controller-manager-config" "context" $) }}
    namespace: {{ .Release.Namespace }}
