apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
    annotations:
        {{- if .Values.certManager.enable }}
        cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "ocular.resourceName" (dict "suffix" "serving-cert" "context" $) }}
        {{- end }}
    name: {{ include "ocular.resourceName" (dict "suffix" "mutating-webhook-configuration" "context" $) }}
webhooks:
    - admissionReviewVersions:
        - v1
      clientConfig:
        service:
            name: {{ include "ocular.resourceName" (dict "suffix" "webhook-service" "context" $) }}
            namespace: {{ .Release.Namespace }}
            path: /mutate-ocular-crashoverride-run-v1beta1-cronsearch
      failurePolicy: Fail
      name: mcronsearch-v1beta1.ocular.crashoverride.run
      rules:
        - apiGroups:
            - ocular.crashoverride.run
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - cronsearches
      sideEffects: None
    - admissionReviewVersions:
        - v1
      clientConfig:
        service:
            name: {{ include "ocular.resourceName" (dict "suffix" "webhook-service" "context" $) }}
            namespace: {{ .Release.Namespace }}
            path: /mutate-ocular-crashoverride-run-v1beta1-pipeline
      failurePolicy: Fail
      name: mpipeline-v1beta1.ocular.crashoverride.run
      rules:
        - apiGroups:
            - ocular.crashoverride.run
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - pipelines
      sideEffects: None
