{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "ocular.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ include "ocular.resourceName" (dict "suffix" "downloader-viewer-role" "context" $) }}
rules:
    - apiGroups:
        - ocular.crashoverride.run
      resources:
        - downloaders
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ocular.crashoverride.run
      resources:
        - downloaders/status
      verbs:
        - get
{{- end }}
