apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "ocular.resourceName" (dict "suffix" "search-cluster-role" "context" $) }}
rules:
    - apiGroups:
        - ocular.crashoverride.run
      resources:
        - pipelines
        - searches
      verbs:
        - get
        - list
        - create
        - update
        - patch
        - delete
