apiVersion: v1
data:
    OCULAR_EXTRACTOR_IMG: "{{ .Values.extractor.image.repository }}:{{ .Values.extractor.image.tag }}"
    OCULAR_EXTRACTOR_PULLPOLICY: IfNotPresent
    OCULAR_SEARCH_CLUSTER_ROLE: ocular-search-cluster-role
kind: ConfigMap
metadata:
    name: ocular-controller-manager-config-dh8htt852d
    namespace: {{ .Release.Namespace }}
