---
apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: ocular-defaults-pypi
spec:
  container:
    image: '{{ .Values.downloaders.image.repository }}:{{ .Values.downloaders.image.tag }}'
    name: pypi
    resources: {}
